name: Version Bumper

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # Required to push version changes and tags

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install bump2version
        run: pip install bump2version

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Bump version
        run: |
          # Read current version
          CURRENT_VERSION=$(cat version.txt)
          echo "Current version: $CURRENT_VERSION"
          
          # Bump patch version
          IFS='.' read -ra VERSION <<< "$CURRENT_VERSION"
          NEW_VERSION="${VERSION[0]}.${VERSION[1]}.$((VERSION[2]+1))"
          echo "New version: $NEW_VERSION"
          
          # Update version file
          echo "$NEW_VERSION" > version.txt
          
          # Update .bumpversion.cfg if exists
          if [ -f .bumpversion.cfg ]; then
            sed -i "s/current_version = .*/current_version = $NEW_VERSION/" .bumpversion.cfg
          fi

      - name: Push version changes
        run: |
          git commit -am "Bump version to $(cat .bumpversion.cfg | grep current_version | awk '{print $3}')"
          git push

      - name: Create and push tag
        run: |
          VERSION=$(cat .bumpversion.cfg | grep current_version | awk '{print $3}')
          git tag "v$VERSION"
          git push origin "v$VERSION"
