name: Version Bumper

on:
  push:
    branches: [ main ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump version
        run: |
          bump2version patch  # or minor/major
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Bump version"
          git push

      - name: Create tag
        run: |
          VERSION=$(cat .bumpversion.cfg | grep current_version | awk '{print $3}')
          git tag "v$VERSION"
          git push origin "v$VERSION"